nodeLinker: node-modules

npmPublishAccess: public

# TEMP: Remove this once we are ready to merge to main branch
changesetBaseRefs: [
  "master",
  "origin/master",
  "upstream/master",
  "main",
  "origin/main",
  "upstream/main",
  "feature-publish-npm",
  "origin/feature-publish-npm",
  "upstream/feature-publish-npm",
]
