name: (Manual) Prepare New Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version Bump Type (major/minor/patch)'
        required: true
        default: 'patch'

jobs:
  prepare-new-release:
    # There is currently no way to limit workflow dispatch to only allow default branch
    # so we need to restrict it here
    # See https://github.community/t/limit-branch-for-workflow-dispatch/122099
    if: github.ref == 'refs/heads/main' && github.repository == 'finos/legend-engine-ide-client-vscode'
    name: Prepare New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
          npm install -g @vscode/vsce
      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Create PR for new release version bump
        env:
          BUMP_TYPE: ${{ github.event.inputs.bump_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./scripts/release/createVersionBumpPR.js
